version: 2.1
orbs:
  node: circleci/node@5.0.0

jobs:
  build:
    docker:
      - image: cimg/node:16.7.0
    steps:
      - checkout
      - install:
          command: |
            cd corbal-react-app
            npm install
      - run:
          command: |
            cd corbal-react-app
            npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
