export const GENRES=["Pop","EDM","ROCK"];

export const spotifyToken = "BQAcqnajEUM5zlVeJlB-0ogmZ_vgeBpzs0AjYYsHzIIC8GQ0KEieqSgLpkD7OrVEQyZh1l2VYSMBPnP6nw9ddJjbJoGKg2y4rhXH4lRfkxlBbMc3Or1bwAoQ_KUa5aWno93m_Glew1yyYNNuY83YMd8DuC9dppmO4YJvkBY"