export const GENRES=["Pop","EDM","ROCK"];

export const spotifyToken = "BQAtTXQ6noqWxILjXJABSl95i7uquAAOBYjfME0ouLKd6pSKXJMCwyUhO_5dag3vRWbq_fu9n8pudlkpTlhI1dwoaYXQOqjso_0P1FRHBzu7heSrAvNfJleVpHZumqip_kly1YU7os3phDfmnbZesNJ0v5d49IfyNObyyHU"